name: foodcomp

services:
  delivery:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Services
      args:
        - serviceName=DeliveryService
        - timeZone=Europe/Berlin
    container_name: delivery-service

  dispatch:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Services
      args:
        - serviceName=DispatchService
        - timeZone=Europe/Berlin
    container_name: dispatch-service

  noether:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Noether
    container_name: noether
    entrypoint: tail -f /dev/null

networks:
  foodcomp:
