name: foodcomp

services:
  delivery:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Services
      args:
        - serviceName=DeliveryService
        - timeZone=Europe/Berlin
    container_name: delivery-service
    env_file:
      - delivery.env

  dispatch:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Services
      args:
        - serviceName=DispatchService
        - timeZone=Europe/Berlin
    container_name: dispatch-service
    env_file:
      - dispatch.env
    depends_on:
      - delivery

  noether:
    build:
      context: ..
      dockerfile: docker/Dockerfile-Noether
    container_name: noether
    entrypoint: tail -f /dev/null
    depends_on:
      - delivery
      - dispatch

networks:
  foodcomp:
