name: foodcomp

services:
  delivery:
    #image: delivery-service
    build:
      context: ..
      dockerfile: docker/Dockerfile-Services
      args:
        - serviceName=DeliveryService
        - timeZone=Europe/Berlin
    container_name: delivery-service

networks:
  foodcomp:
