FROM alpine:latest

# Install packages
RUN apk update
RUN apk add bash
RUN apk add curl
RUN apk add jq

# Setup bash aliases
RUN echo "alias deliveries='curl -s delivery-service/deliveries | jq'" > ~/.bashrc
RUN echo "alias dispatches='curl -s dispatch-service/dispatches | jq'" >> ~/.bashrc

# Provide keep alive script to keep idle container running in compose context
# TODO: Execute script directly from compose without creating this file
RUN echo 'trap "exit" SIGTERM; while true; do sleep 1; done' > /bin/compose_keep_alive
RUN chmod +x /bin/compose_keep_alive

ENTRYPOINT [ "/bin/bash" ]
